### ISSUE TITLE
heaving this error when creating/saving a fitting 

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-fitting-manager#30]
i get a error when trying to add an EFT fitting then save. If i don't add any EFT fitting then it saves ok but if i do add items in the EFT fitting box then click on update/save i get an  HTTP ERROR 500

This is what im adding in the EFT fittings box:
```
[Venture, Newbie miner]
EP-S Gaussian Scoped Mining Laser
EP-S Gaussian Scoped Mining Laser
Salvager I

1MN Monopropellant Enduring Afterburner
Medium Azeotropic Restrained Shield Extender
ML-3 Scoped Survey Scanner

Mining Laser Upgrade I


Hobgoblin I x2
```

here is the PHP error i get in my logs:

`Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function prepare() on boolean in /wp-content/plugins/eve-online-fitting-manager/Libs/Helper/FittingHelper.php:286\nStack trace:\n#0 /wp-content/plugins/eve-online-fitting-manager/Libs/MetaBoxes.php(142): WordPress\\Plugin\\EveOnlineFittingManager\\Libs\\Helper\\FittingHelper::getItemIdByName('Venture')\n#1 /wp-includes/class-wp-hook.php(300): WordPress\\Plugin\\EveOnlineFittingManager\\Libs\\MetaBoxes->saveMetaBoxes(149)\n#2 /wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)\n#3 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#4 /wp-includes/post.php(3510): do_action('save_post', 149, Object(WP_Post), false)\n#5 /va...\n', referer: /wp-admin/post-new.php?post_type=fitting&wp-post-new-reload=true`

How can i fix it?

i did try master and tag v0.13.2 and v0.12 but getting the same bug :(

**Comment by ppfeufer** [comment]
You have the EDK Killboard Database configured?

**Comment by raykai** [comment]
Nop would need to know how to do that any instructions for it ? 

I was also wondering if you know of a plugin that works with login in WordPress using the EvE online SSO... from what i see there is a big demand for this.

i love your work so far keep it up :)

**Comment by ppfeufer** [comment]
Ya, I just realized, I haven't covered that part in the readme. Apologies.

You need a EDK Killboard Database for this plugin, because it gets all the ship and module information from that database. So if you are running a self hosted killboard, just go to the Plugin Settings in your WordPress backend and enter the database details there. If you don't run a self hosted killboard, well that plugin won't work ... for now. And rewrite to use the ESI API is in the making, but since the ESI is still very unstable and wonky at best it might still take quite some time.

**Comment by raykai** [comment]
ok so i need to be running this right http://www.evekb.org/  i just finished installing it il connect em tomorrow. :)

The only thing that's missing is a WordPress login with eve online SSO plugin for WordPress but can't seem to find any. this would be good for all the small corps.

**Comment by ppfeufer** [comment]
Yep, that's exactly what you need.

Regarding the SSO Plugin, there is one, but that doesn't work properly and requires an account on a 3rd party service which I can't recommend to do. Besides that, nothing known to me.
