### ISSUE TITLE
Cannot save EFT Fots

### ISSUE THREAD

**Issue by gate0keeper** [ppfeufer/eve-online-fitting-manager#33]
Hi,

I just installed that plugin as I love the functionallity and definitly want to use it for my corps page.
So when trying to save a fit I get a 500 Error. Than, when reloading WP and looking into the fits, that one was saved, but, when entering in the fit, the EFT column is empty, also there is no more textbox left in that column. Please help me out :)

Thanks and cheers,
Daniel

**Comment by ppfeufer** [comment]
You need a local EDK (Kill Board) Installation and add the database details in the plugins settings.

**Comment by gate0keeper** [comment]
Thanks for your Info, I got it. If you don´t mind, I would like to ask some more questions.
As I have it running now, I did not get that menu showing doctrines, aaliance, corp etc. I have created doctrines in backend, also fittings, but I just can access them with original links. Is it intended, or does that menu excists in final plugin?

**Comment by ppfeufer** [comment]
Make sure you have set the page template to "Fittings", so WordPress actually recognizes the page as the start page for the fittings stuff, and than just throw the shortcode ```[fittings]``` in there.

**Comment by gate0keeper** [comment]
Thx a lot, that shortcode I was missing. Now it works fine, just have to adapt to my theme.

Cheers, Daniel

**Comment by gate0keeper** [comment]
Wir hätten aber auch deutsch schreiben können :)
