### ISSUE TITLE
Error as of 1.4.4

### ISSUE THREAD

**Issue by waltari** [ppfeufer/eve-online-fitting-manager#48]
getting this always when i try to add new fittings

Fatal error: Uncaught TypeError: Argument 1 passed to WordPress\Plugins\EveOnlineFittingManager\Libs\Helper\EsiHelper::getItemTypeInformation() must be of the type integer, string given, called in /srv/_container/_1000066/web/content/www/wp-content/plugins/eve-online-fitting-manager/Libs/Helper/FittingHelper.php on line 192 and defined in /srv/_container/_1000066/web/content/www/wp-content/plugins/eve-online-fitting-manager/Libs/Helper/EsiHelper.php:167 Stack trace: #0 /srv/_container/_1000066/web/content/www/wp-content/plugins/eve-online-fitting-manager/Libs/Helper/FittingHelper.php(192): WordPress\Plugins\EveOnlineFittingManager\Libs\Helper\EsiHelper->getItemTypeInformation('') #1 /srv/_container/_1000066/web/content/www/wp-content/plugins/eve-online-fitting-manager/Libs/Helper/EftHelper.php(299): WordPress\Plugins\EveOnlineFittingManager\Libs\Helper\FittingHelper->getItemNameById('') #2 /srv/_container/_1000066/web/content/www/wp-content/plugins/eve-online-fitting-manager/Libs/MetaBoxes.php(72): WordPress\Plugins\EveOn in /srv/_container/_1000066/web/content/www/wp-content/plugins/eve-online-fitting-manager/Libs/Helper/EsiHelper.php on line 167

previous 1.4.2 seems ok

**Comment by ppfeufer** [comment]
Can you please post the fitting you are trying to add?

**Comment by waltari** [comment]
yes, prety much copy/pasting fits from E-Uni

[Caracal Navy Issue, Sovereign]
Rapid Light Missile Launcher II
Rapid Light Missile Launcher II
Rapid Light Missile Launcher II
Rapid Light Missile Launcher II
Rapid Light Missile Launcher II

Large Shield Extender II
Large Shield Extender II
50MN Cold-Gas Enduring Microwarpdrive
Adaptive Invulnerability Field II
Warp Disruptor II

Ballistic Control System II
Ballistic Control System II
Ballistic Control System II
Damage Control II

Medium Anti-EM Screen Reinforcer II
Medium Core Defense Field Extender II
Medium Core Defense Field Extender II


Caldari Navy Inferno Light Missile x1000

and

[Blackbird, EUNI Blackbird - Standard]
Light Missile Launcher II
Light Missile Launcher II
Light Missile Launcher II

50MN Cold-Gas Enduring Microwarpdrive
Conjunctive Gravimetric ECCM Scanning Array I
Enfeebling Phase Inversion ECM I
BZ-5 Neutralizing Spatial Destabilizer ECM
'Umbra' White Noise ECM
'Hypnos' Ion Field ECM I

1600mm Rolled Tungsten Compact Plates
Signal Distortion Amplifier II
Damage Control II

Medium Particle Dispersion Augmentor I
Medium Particle Dispersion Augmentor I

Warrior II x2

EDIT: Maybe old module names and/or wrong slot layout rite?

**Comment by ppfeufer** [comment]
I actually had a different Idea why it's breaking. Sometimes in fittings you find these "[Empty High Slot]" Lines, which are of course no valid modules and were breaking the script, which I fixed and will be shipped out with the next version.

Despite the fact that the slot order is messed up in th efittings you posted, I can import at least the Caracal without any issues.
![Selection_103](https://user-images.githubusercontent.com/2989985/64064360-8ed68300-cc00-11e9-974d-10c2f2cd8199.jpg)
As for the Blackbird, the "Conjunctive Gravimetric ECCM Scanning Array I" doesn't exist any longer with that name. Dont ask me what it's called nowadays. I'll add some sort of failcheck for stuff like this ...

For now, stick with the 1.4.2 version, fixes will be shipped with the next release.

**Comment by waltari** [comment]
thanks a lot <3

**Comment by ppfeufer** [comment]
OK, the fix is actually easier than I initially thought. On that Blackbird Fitting basically all the mosules in the mid slots are old and don't exist anymore besided the MWD...

![Selection_104](https://user-images.githubusercontent.com/2989985/64064458-ec1f0400-cc01-11e9-91b1-ace2a88c800c.jpg)
This is hot it would look like ...

What I'm doing here is just ignoring anything I can't get a proper EVE Item ID for ...

**Comment by waltari** [comment]
Just figured out that Pyfa is able to convert old module names to new ones so the onlz thing i have to do is delete the [empty high slot] and [empty rig slot]
![image](https://user-images.githubusercontent.com/6461794/64064532-10c7ab80-cc03-11e9-9410-f4668167f542.png)

**Comment by ppfeufer** [comment]
Ah nice to know, so Pyfa seems to have some sort of old names list or what ever. Unfortunately I can't do stuff like that, because I simply trigger ESI to get the informations and the old names are not available there :-(

But I updated the plugin, new version should be available soon in your updates page.
